version: "3.5"
  
services: 

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${HOMEASSISTANT_TAG}"
    volumes:
      - ./volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    expose:
      - 8123
    network_mode: host
